<template>
  <a-card :bordered="false" :class="'cust-erp-sub-tab'">

    <!-- 操作按钮区域 -->
    <div class="table-operator" :md="24" :sm="24" style="margin: 0px 0px 20px 0px">

      <a-dropdown v-if="selectedRowKeys.length > 0">
        <a-menu slot="overlay">
          <a-menu-item key="1" @click="batchDel">
            <a-icon type="delete"/>
            删除
          </a-menu-item>
        </a-menu>
        <a-button style="margin-left: 8px"> 批量操作
          <a-icon type="down"/>
        </a-button>
      </a-dropdown>
    </div>

    <!-- table区域-begin -->
    <div>
      <div class="ant-alert ant-alert-info" style="margin-bottom: 16px;">
        <i class="anticon anticon-info-circle ant-alert-icon"></i> 已选择 <a style="font-weight: 600">{{
          selectedRowKeys.length
        }}</a>项
        <a style="margin-left: 24px" @click="onClearSelected">清空</a>
      </div>

      <a-table
        ref="table"
        size="middle"
        bordered
        rowKey="id"
        :columns="columns"
        :dataSource="dataSource"
        :pagination="ipagination"
        :loading="loading"
        :rowSelection="{selectedRowKeys: selectedRowKeys, onChange: onSelectChange}"
        @change="handleTableChange">

        <div slot="level" slot-scope="text,record" style="margin: 0">
          <template v-if="record.name[16]%2===1">
            <template
              v-if="record.matchItem==='50米自由泳'&&record.matchScore<=3350&&record.matchScore>2650&&record.distance==='25'">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=3450&&record.matchScore>2750&&record.distance==='50'">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=2650&&record.matchScore>2350&&record.distance==='25'">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=2750&&record.matchScore>2450&&record.distance==='50'">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=2350&&record.matchScore>2228&&record.distance==='25'">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=2450&&record.matchScore>2328&&record.distance==='50'">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=2228&&record.matchScore>2095&&record.distance==='25'">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=2328&&record.matchScore>2195&&record.distance==='50'">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=2095&&record.matchScore>0&&record.distance==='25'">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=2195&&record.matchScore>0&&record.distance==='50'">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='25'&&record.matchScore<=4689&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='50'&&record.matchScore<=4839&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='25'&&record.matchScore<=5000&&record.matchScore>4689">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='50'&&record.matchScore<=5150&&record.matchScore>4839">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='25'&&record.matchScore<=5400&&record.matchScore>5000">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='50'&&record.matchScore<=5550&&record.matchScore>5150">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='25'&&record.matchScore<=10350&&record.matchScore>5400">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='50'&&record.matchScore<=10500&&record.matchScore>5550">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='25'&&record.matchScore<=12050&&record.matchScore>10350">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='50'&&record.matchScore<=12200&&record.matchScore>10500">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='25'&&record.matchScore<=14340&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='50'&&record.matchScore<=14690&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='25'&&record.matchScore<=14810&&record.matchScore>14340">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='50'&&record.matchScore<=15150&&record.matchScore>14690">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='25'&&record.matchScore<=15950&&record.matchScore>14810">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='50'&&record.matchScore<=20300&&record.matchScore>15150">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='25'&&record.matchScore<=21950&&record.matchScore>15950">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='50'&&record.matchScore<=22300&&record.matchScore>20300">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='25'&&record.matchScore<=25250&&record.matchScore>21950">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='50'&&record.matchScore<=25600&&record.matchScore>22300">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='25'&&record.matchScore<=34080&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='50'&&record.matchScore<=34780&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='25'&&record.matchScore<=35160&&record.matchScore>34080">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='50'&&record.matchScore<=35860&&record.matchScore>34780">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='25'&&record.matchScore<=41400&&record.matchScore>35160">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='50'&&record.matchScore<=42100&&record.matchScore>35860">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='25'&&record.matchScore<=45900&&record.matchScore>41400">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='50'&&record.matchScore<=50600&&record.matchScore>42100">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='25'&&record.matchScore<=61150&&record.matchScore>45900">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='50'&&record.matchScore<=61600&&record.matchScore>50600">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='25'&&record.matchScore<=74610&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='50'&&record.matchScore<=80010&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='25'&&record.matchScore<=81000&&record.matchScore>74610">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='50'&&record.matchScore<=82400&&record.matchScore>80010">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='25'&&record.matchScore<=84800&&record.matchScore>81000">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='50'&&record.matchScore<=90200&&record.matchScore>82400">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='25'&&record.matchScore<=101800&&record.matchScore>84800">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='50'&&record.matchScore<=103200&&record.matchScore>90200">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='25'&&record.matchScore<=125800&&record.matchScore>101800">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='50'&&record.matchScore<=131200&&record.matchScore>103200">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='25'&&record.matchScore<=144710&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='50'&&record.matchScore<=151210&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='25'&&record.matchScore<=153530&&record.matchScore>144710">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='50'&&record.matchScore<=160030&&record.matchScore>151210">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='25'&&record.matchScore<=165400&&record.matchScore>153530">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='50'&&record.matchScore<=172000&&record.matchScore>160030">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='25'&&record.matchScore<=195000&&record.matchScore>165400">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='50'&&record.matchScore<=201500&&record.matchScore>172000">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='25'&&record.matchScore<=242000&&record.matchScore>195000">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='50'&&record.matchScore<=244500&&record.matchScore>201500">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='25'&&record.matchScore<=2424&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='50'&&record.matchScore<=2524&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='25'&&record.matchScore<=2643&&record.matchScore>2424">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='50'&&record.matchScore<=2743&&record.matchScore>2524">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='25'&&record.matchScore<=2950&&record.matchScore>2643">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='50'&&record.matchScore<=3050&&record.matchScore>2743">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='25'&&record.matchScore<=3450&&record.matchScore>2950">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='50'&&record.matchScore<=3550&&record.matchScore>3050">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='25'&&record.matchScore<=4200&&record.matchScore>3450">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='50'&&record.matchScore<=4300&&record.matchScore>3550">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='25'&&record.matchScore<=5292&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='50'&&record.matchScore<=5392&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='25'&&record.matchScore<=5745&&record.matchScore>5292">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='50'&&record.matchScore<=5845&&record.matchScore>5392">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='25'&&record.matchScore<=10300&&record.matchScore>5745">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='50'&&record.matchScore<=10400&&record.matchScore>5845">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='25'&&record.matchScore<=11300&&record.matchScore>10300">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='50'&&record.matchScore<=11400&&record.matchScore>10400">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='25'&&record.matchScore<=12900&&record.matchScore>11300">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='50'&&record.matchScore<=13000&&record.matchScore>11400">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='25'&&record.matchScore<=15590&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='50'&&record.matchScore<=15790&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='25'&&record.matchScore<=20450&&record.matchScore>15590">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='50'&&record.matchScore<=20650&&record.matchScore>15790">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='25'&&record.matchScore<=21600&&record.matchScore>20450">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='50'&&record.matchScore<=21800&&record.matchScore>20650">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='25'&&record.matchScore<=23900&&record.matchScore>21600">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='50'&&record.matchScore<=24100&&record.matchScore>21800">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='25'&&record.matchScore<=31300&&record.matchScore>23900">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='50'&&record.matchScore<=31600&&record.matchScore>24100">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='25'&&record.matchScore<=2647&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='50'&&record.matchScore<=2747&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='25'&&record.matchScore<=2775&&record.matchScore>2647">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='50'&&record.matchScore<=2875&&record.matchScore>2747">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='25'&&record.matchScore<=3150&&record.matchScore>2775">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='50'&&record.matchScore<=3250&&record.matchScore>2875">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='25'&&record.matchScore<=3600&&record.matchScore>3150">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='50'&&record.matchScore<=3700&&record.matchScore>3250">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='25'&&record.matchScore<=4300&&record.matchScore>3600">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='50'&&record.matchScore<=4400&&record.matchScore>3700">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='25'&&record.matchScore<=5823&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='50'&&record.matchScore<=10020&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='25'&&record.matchScore<=10180&&record.matchScore>5823">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='50'&&record.matchScore<=10380&&record.matchScore>10020">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='25'&&record.matchScore<=10900&&record.matchScore>10180">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='50'&&record.matchScore<=11100&&record.matchScore>10380">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='25'&&record.matchScore<=11800&&record.matchScore>10900">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='50'&&record.matchScore<=12000&&record.matchScore>11100">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='25'&&record.matchScore<=13200&&record.matchScore>11800">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='50'&&record.matchScore<=13400&&record.matchScore>12000">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='25'&&record.matchScore<=20780&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='50'&&record.matchScore<=21170&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='25'&&record.matchScore<=21790&&record.matchScore>20780">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='50'&&record.matchScore<=22190&&record.matchScore>21170">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='25'&&record.matchScore<=23100&&record.matchScore>21790">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='50'&&record.matchScore<=23500&&record.matchScore>22190">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='25'&&record.matchScore<=25000&&record.matchScore>23100">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='50'&&record.matchScore<=25400&&record.matchScore>23500">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='25'&&record.matchScore<=31900&&record.matchScore>25000">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='50'&&record.matchScore<=32300&&record.matchScore>25400">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='25'&&record.matchScore<=2251&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='50'&&record.matchScore<=2351&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='25'&&record.matchScore<=2389&&record.matchScore>2251">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='50'&&record.matchScore<=2489&&record.matchScore>2351">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='25'&&record.matchScore<=2600&&record.matchScore>2389">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='50'&&record.matchScore<=2700&&record.matchScore>2489">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='25'&&record.matchScore<=3150&&record.matchScore>2600">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='50'&&record.matchScore<=3250&&record.matchScore>2700">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='25'&&record.matchScore<=4050&&record.matchScore>3150">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='50'&&record.matchScore<=4150&&record.matchScore>3250">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='25'&&record.matchScore<=5042&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='50'&&record.matchScore<=5192&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='25'&&record.matchScore<=5395&&record.matchScore>5042">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='50'&&record.matchScore<=5545&&record.matchScore>5192">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='25'&&record.matchScore<=5850&&record.matchScore>5395">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='50'&&record.matchScore<=10000&&record.matchScore>5545">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='25'&&record.matchScore<=10950&&record.matchScore>5850">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='50'&&record.matchScore<=11100&&record.matchScore>10000">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='25'&&record.matchScore<=12750&&record.matchScore>10950">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='50'&&record.matchScore<=12900&&record.matchScore>11100">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='25'&&record.matchScore<=15360&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='50'&&record.matchScore<=15660&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='25'&&record.matchScore<=15970&&record.matchScore>15360">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='50'&&record.matchScore<=20270&&record.matchScore>15660">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='25'&&record.matchScore<=21100&&record.matchScore>15970">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='50'&&record.matchScore<=21400&&record.matchScore>20270">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='25'&&record.matchScore<=23500&&record.matchScore>21100">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='50'&&record.matchScore<=23800&&record.matchScore>21400">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='25'&&record.matchScore<=31500&&record.matchScore>23500">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='50'&&record.matchScore<=31800&&record.matchScore>23800">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='25'&&record.matchScore<=15680&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='50'&&record.matchScore<=15980&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='25'&&record.matchScore<=20520&&record.matchScore>15680">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='50'&&record.matchScore<=20820&&record.matchScore>15980">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='25'&&record.matchScore<=21600&&record.matchScore>20520">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='50'&&record.matchScore<=21900&&record.matchScore>20820">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='25'&&record.matchScore<=23700&&record.matchScore>21600">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='50'&&record.matchScore<=24000&&record.matchScore>21900">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='25'&&record.matchScore<=31200&&record.matchScore>23700">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='50'&&record.matchScore<=31500&&record.matchScore>24000">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='25'&&record.matchScore<=41200&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='50'&&record.matchScore<=41810&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='25'&&record.matchScore<=42520&&record.matchScore>41200">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='50'&&record.matchScore<=43120&&record.matchScore>41810">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='25'&&record.matchScore<=45200&&record.matchScore>42520">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='50'&&record.matchScore<=45830&&record.matchScore>43120">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='25'&&record.matchScore<=52500&&record.matchScore>45200">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='50'&&record.matchScore<=53100&&record.matchScore>45830">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='25'&&record.matchScore<=65000&&record.matchScore>52500">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='50'&&record.matchScore<=65600&&record.matchScore>53100">
              三级
            </template>
            <template v-else>-</template>
          </template>
          <template v-else-if="record.name[16]%2===0">
            <template
              v-if="record.matchItem==='50米自由泳'&&record.matchScore<=3750&&record.matchScore>3050&&record.distance==='25'">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=3850&&record.matchScore>3150&&record.distance==='50'">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=3050&&record.matchScore>2620&&record.distance==='25'">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=3150&&record.matchScore>2720&&record.distance==='50'">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=2620&&record.matchScore>2485&&record.distance==='25'">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=2720&&record.matchScore>2585&&record.distance==='50'">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=2485&&record.matchScore>2390&&record.distance==='25'">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=2585&&record.matchScore>2490&&record.distance==='50'">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=2390&&record.matchScore>0&&record.distance==='25'">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='50米自由泳'&&record.matchScore<=2490&&record.matchScore>0&&record.distance==='50'">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='25'&&record.matchScore<=5285&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='50'&&record.matchScore<=5435&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='25'&&record.matchScore<=5480&&record.matchScore>5285">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='50'&&record.matchScore<=5630&&record.matchScore>5435">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='25'&&record.matchScore<=10100&&record.matchScore>5480">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='50'&&record.matchScore<=10250&&record.matchScore>5630">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='25'&&record.matchScore<=11100&&record.matchScore>10100">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='50'&&record.matchScore<=11300&&record.matchScore>10250">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='25'&&record.matchScore<=13300&&record.matchScore>11100">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='100米自由泳'&&record.distance==='50'&&record.matchScore<=13400&&record.matchScore>11300">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='25'&&record.matchScore<=15430&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='50'&&record.matchScore<=15780&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='25'&&record.matchScore<=15770&&record.matchScore>15430">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='50'&&record.matchScore<=20120&&record.matchScore>15780">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='25'&&record.matchScore<=21150&&record.matchScore>15770">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='50'&&record.matchScore<=21500&&record.matchScore>20120">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='25'&&record.matchScore<=23550&&record.matchScore>21150">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='50'&&record.matchScore<=23900&&record.matchScore>21500">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='25'&&record.matchScore<=31950&&record.matchScore>23550">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米自由泳'&&record.distance==='50'&&record.matchScore<=32300&&record.matchScore>23900">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='25'&&record.matchScore<=40220&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='50'&&record.matchScore<=40920&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='25'&&record.matchScore<=40880&&record.matchScore>40220">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='50'&&record.matchScore<=41580&&record.matchScore>40920">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='25'&&record.matchScore<=43700&&record.matchScore>40880">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='50'&&record.matchScore<=44400&&record.matchScore>41580">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='25'&&record.matchScore<=53900&&record.matchScore>43700">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='50'&&record.matchScore<=54600&&record.matchScore>44400">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='25'&&record.matchScore<=65900&&record.matchScore>53900">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='400米自由泳'&&record.distance==='50'&&record.matchScore<=70600&&record.matchScore>54600">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='25'&&record.matchScore<=82000&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='50'&&record.matchScore<=83390&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='25'&&record.matchScore<=83940&&record.matchScore>82000">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='50'&&record.matchScore<=85340&&record.matchScore>83390">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='25'&&record.matchScore<=92800&&record.matchScore>83940">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='50'&&record.matchScore<=94200&&record.matchScore>85340">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='25'&&record.matchScore<=114800&&record.matchScore>92800">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='50'&&record.matchScore<=120200&&record.matchScore>94200">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='25'&&record.matchScore<=144800&&record.matchScore>114800">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='800米自由泳'&&record.distance==='50'&&record.matchScore<=150200&&record.matchScore>120200">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='25'&&record.matchScore<=161250&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='50'&&record.matchScore<=163740&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='25'&&record.matchScore<=164900&&record.matchScore>161250">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='50'&&record.matchScore<=171400&&record.matchScore>163740">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='25'&&record.matchScore<=181000&&record.matchScore>164900">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='50'&&record.matchScore<=183500&&record.matchScore>171400">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='25'&&record.matchScore<=232000&&record.matchScore>181000">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='50'&&record.matchScore<=234500&&record.matchScore>183500">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='25'&&record.matchScore<=272000&&record.matchScore>232000">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='1500米自由泳'&&record.distance==='50'&&record.matchScore<=274500&&record.matchScore>234500">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='25'&&record.matchScore<=2761&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='50'&&record.matchScore<=2861&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='25'&&record.matchScore<=2955&&record.matchScore>2761">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='50'&&record.matchScore<=3055&&record.matchScore>2861">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='25'&&record.matchScore<=3200&&record.matchScore>2955">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='50'&&record.matchScore<=3300&&record.matchScore>3055">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='25'&&record.matchScore<=3750&&record.matchScore>3200">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='50'&&record.matchScore<=3850&&record.matchScore>3300">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='25'&&record.matchScore<=4550&&record.matchScore>3750">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='50米仰泳'&&record.distance==='50'&&record.matchScore<=4650&&record.matchScore>3850">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='25'&&record.matchScore<=5969&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='50'&&record.matchScore<=10070&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='25'&&record.matchScore<=10330&&record.matchScore>5969">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='50'&&record.matchScore<=10430&&record.matchScore>10070">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='25'&&record.matchScore<=10800&&record.matchScore>10330">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='50'&&record.matchScore<=10900&&record.matchScore>10430">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='25'&&record.matchScore<=12000&&record.matchScore>10800">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='50'&&record.matchScore<=12100&&record.matchScore>10900">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='25'&&record.matchScore<=14000&&record.matchScore>12000">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='100米仰泳'&&record.distance==='50'&&record.matchScore<=14100&&record.matchScore>12100">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='25'&&record.matchScore<=20810&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='50'&&record.matchScore<=21010&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='25'&&record.matchScore<=21630&&record.matchScore>20810">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='50'&&record.matchScore<=21830&&record.matchScore>21010">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='25'&&record.matchScore<=22700&&record.matchScore>21630">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='50'&&record.matchScore<=22950&&record.matchScore>21830">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='25'&&record.matchScore<=25100&&record.matchScore>22700">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='50'&&record.matchScore<=25300&&record.matchScore>22950">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='25'&&record.matchScore<=33650&&record.matchScore>25100">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米仰泳'&&record.distance==='50'&&record.matchScore<=33850&&record.matchScore>25300">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='25'&&record.matchScore<=3023&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='50'&&record.matchScore<=3123&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='25'&&record.matchScore<=3070&&record.matchScore>3023">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='50'&&record.matchScore<=3170&&record.matchScore>3123">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='25'&&record.matchScore<=3500&&record.matchScore>3070">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='50'&&record.matchScore<=3600&&record.matchScore>3170">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='25'&&record.matchScore<=4000&&record.matchScore>3500">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='50'&&record.matchScore<=4100&&record.matchScore>3600">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='25'&&record.matchScore<=4700&&record.matchScore>4000">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='50米蛙泳'&&record.distance==='50'&&record.matchScore<=4800&&record.matchScore>4100">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='25'&&record.matchScore<=10540&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='50'&&record.matchScore<=10740&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='25'&&record.matchScore<=10870&&record.matchScore>10540">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='50'&&record.matchScore<=11070&&record.matchScore>10740">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='25'&&record.matchScore<=11600&&record.matchScore>10870">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='50'&&record.matchScore<=11800&&record.matchScore>11070">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='25'&&record.matchScore<=12700&&record.matchScore>11600">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='50'&&record.matchScore<=12900&&record.matchScore>11800">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='25'&&record.matchScore<=14200&&record.matchScore>12700">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='100米蛙泳'&&record.distance==='50'&&record.matchScore<=14400&&record.matchScore>12900">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='25'&&record.matchScore<=22120&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='50'&&record.matchScore<=22520&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='25'&&record.matchScore<=23260&&record.matchScore>22120">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='50'&&record.matchScore<=23660&&record.matchScore>22520">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='25'&&record.matchScore<=24700&&record.matchScore>23260">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='50'&&record.matchScore<=25100&&record.matchScore>23660">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='25'&&record.matchScore<=30900&&record.matchScore>24700">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='50'&&record.matchScore<=31300&&record.matchScore>25100">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='25'&&record.matchScore<=34400&&record.matchScore>30900">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米蛙泳'&&record.distance==='50'&&record.matchScore<=34800&&record.matchScore>31300">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='25'&&record.matchScore<=2547&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='50'&&record.matchScore<=2647&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='25'&&record.matchScore<=2650&&record.matchScore>2547">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='50'&&record.matchScore<=2750&&record.matchScore>2647">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='25'&&record.matchScore<=2950&&record.matchScore>2650">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='50'&&record.matchScore<=3050&&record.matchScore>2750">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='25'&&record.matchScore<=3550&&record.matchScore>2950">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='50'&&record.matchScore<=3650&&record.matchScore>3050">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='25'&&record.matchScore<=4450&&record.matchScore>3550">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='50米蝶泳'&&record.distance==='50'&&record.matchScore<=4550&&record.matchScore>3650">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='25'&&record.matchScore<=5661&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='50'&&record.matchScore<=5811&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='25'&&record.matchScore<=5900&&record.matchScore>5661">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='50'&&record.matchScore<=10050&&record.matchScore>5811">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='25'&&record.matchScore<=10650&&record.matchScore>5900">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='50'&&record.matchScore<=10800&&record.matchScore>10050">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='25'&&record.matchScore<=11850&&record.matchScore>10650">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='50'&&record.matchScore<=12000&&record.matchScore>10800">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='25'&&record.matchScore<=13750&&record.matchScore>11850">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='100米蝶泳'&&record.distance==='50'&&record.matchScore<=13900&&record.matchScore>12000">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='25'&&record.matchScore<=20580&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='50'&&record.matchScore<=20880&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='25'&&record.matchScore<=21120&&record.matchScore>20580">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='50'&&record.matchScore<=21420&&record.matchScore>20880">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='25'&&record.matchScore<=22200&&record.matchScore>21120">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='50'&&record.matchScore<=22500&&record.matchScore>21420">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='25'&&record.matchScore<=25150&&record.matchScore>22200">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='50'&&record.matchScore<=25450&&record.matchScore>22500">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='25'&&record.matchScore<=33500&&record.matchScore>25150">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米蝶泳'&&record.distance==='50'&&record.matchScore<=33800&&record.matchScore>25450">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='25'&&record.matchScore<=20980&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='50'&&record.matchScore<=21280&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='25'&&record.matchScore<=21540&&record.matchScore>20980">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='50'&&record.matchScore<=21840&&record.matchScore>21280">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='25'&&record.matchScore<=22700&&record.matchScore>21540">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='50'&&record.matchScore<=23000&&record.matchScore>21840">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='25'&&record.matchScore<=25500&&record.matchScore>22700">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='50'&&record.matchScore<=25800&&record.matchScore>23000">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='25'&&record.matchScore<=34500&&record.matchScore>25500">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='200米混合泳'&&record.distance==='50'&&record.matchScore<=34800&&record.matchScore>25800">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='25'&&record.matchScore<=43560&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='50'&&record.matchScore<=44160&&record.matchScore>0">
              国际级健将
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='25'&&record.matchScore<=45080&&record.matchScore>43560">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='50'&&record.matchScore<=45680&&record.matchScore>44160">
              运动健将
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='25'&&record.matchScore<=51200&&record.matchScore>45080">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='50'&&record.matchScore<=51800&&record.matchScore>45680">
              一级
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='25'&&record.matchScore<=61500&&record.matchScore>51200">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='50'&&record.matchScore<=62100&&record.matchScore>51800">
              二级
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='25'&&record.matchScore<=80000&&record.matchScore>61500">
              三级
            </template>
            <template
              v-else-if="record.matchItem==='400米混合泳'&&record.distance==='50'&&record.matchScore<=80600&&record.matchScore>62100">
              三级
            </template>
            <template v-else>-</template>
          </template>
        </div>

        <template slot="paiming" slot-scope="text, record, index">
          <div class="anty-img-wrap">
            <img :src="getAvatarView(record.avatar)"/>
          </div>
        </template>

        <span slot="action" slot-scope="text, record">
          <a @click="handleEdit(record)">编辑</a>
          <a-divider type="vertical"/>
          <a-dropdown>
            <a class="ant-dropdown-link">
              更多 <a-icon type="down"/>
            </a>
            <a-menu slot="overlay">
              <a-menu-item>
                <a href="javascript:;" @click="handleDetail(record)">详情</a>
              </a-menu-item>
              <a-menu-item>
                <a-popconfirm title="确定删除吗?" @confirm="() => handleDelete(record.id)">
                  <a>删除</a>
                </a-popconfirm>
              </a-menu-item>
            </a-menu>
          </a-dropdown>
        </span>

      </a-table>
    </div>
    <!-- table区域-end -->

    <!-- 表单区域 -->
    <MatchScore-modal ref="modalForm" @ok="modalFormOk"/>
  </a-card>
</template>

<script>
import MatchScoreModal from './modules/MatchScoreModal'
import { JeecgListMixin } from '@/mixins/JeecgListMixin'
import { getAction } from '@/api/manage'
import { queryallll } from '@/api/api'

export default {
  name: 'MatchScoreList',
  mixins: [JeecgListMixin],
  components: {
    MatchScoreModal,
  },
  data() {
    return {
      description: '信息',
      memberList: [],
      selectedMember: [],
      // 表头
      columns: [
        {
          title: '比赛项目',
          align: 'center',
          dataIndex: 'matchItem'
        },
        {
          title: '比赛日期',
          align: 'center',
          width: 100,
          dataIndex: 'matchDate'
        },
        {
          title: '比赛阶段',
          align: 'center',
          width: 100,
          dataIndex: 'matchName'
        },
        {
          title: '场次',
          align: 'center',
          dataIndex: 'changCi',
          sorter: (a, b) => a.changCi - b.changCi,
        },
        {
          title: '项次',
          align: 'center',
          dataIndex: 'xiangCi',
          sorter: (a, b) => a.xiangCi - b.xiangCi,
        },
        {
          title: '道次',
          align: 'center',
          dataIndex: 'daoCi'
        },
        {
          title: '成绩',
          align: 'center',
          dataIndex: 'matchScore',
          customRender: function (t, r, index) {
            return String(parseInt(r.matchScore / 10000 % 10)) + ':' + parseInt(r.matchScore / 1000 % 10) + parseInt(r.matchScore / 100 % 10) + ':' + parseInt(r.matchScore / 10 % 10) + parseInt(r.matchScore % 10)
            // return parseInt(r.matchScore / 10000 % 10) + ':' + parseInt(r.matchScore / 1000 % 10) + parseInt(r.matchScore / 100 % 10) + '.' + parseInt(r.matchScore / 10 % 10) + parseInt(r.matchScore % 10)
          }
        },
        {
          title: '名次',
          align: 'center',
          dataIndex: 'mingCi'
        },
        {
          title: '等级标准',
          dataIndex: 'name',
          align: 'center',
          width: 130,
          scopedSlots: { customRender: 'level' },
        },
        {
          title: '操作',
          key: 'operation',
          align: 'center',
          width: 130,
          scopedSlots: { customRender: 'action' },
        }],
      url: {
        imgerver: window._CONFIG['domianURL'] + '/sys/common/view',
        list: '/match/matchTotal/listMatchScoreByMainId',
        delete: '/match/matchTotal/deleteMatchScore',
        deleteBatch: '/match/matchTotal/deleteBatchMatchScore',
      }
    }
  },
  methods: {
    getAvatarView: function (avatar) {
      return this.url.imgerver + '/' + avatar
    },
    loadData(arg) {
      if (arg === 1) {
        this.ipagination.current = 1
      }
      var params = this.getQueryParams()
      //params.selectionRows.
      getAction(this.url.list, { mainId: params.mainId }).then((res) => {
        if (res.success) {
          this.dataSource = res.result
        } else {
          this.dataSource = null
        }
      })
      queryallll().then((res) => {
        if (res.success) {
          this.memberList = res.result
        } else {
          console.log(res.message)
        }
      })
    },
    getMain(mainId) {
      this.queryParam.mainId = mainId
      this.loadData(1)
    },
    handleAdd: function () {
      this.$refs.modalForm.add(this.queryParam.mainId)
      this.$refs.modalForm.title = '添加比赛成绩'
    },
  }
}
</script>
<style scoped>
.anty-img-wrap {
  height: 50px;
  position: relative;
  width: 50px;
  text-align: center;
  border-radius: 50%;
  overflow: hidden;

img {
  height: 100%;
  width: 100%;
}

}

.anty-img-wrap > img {
  max-height: 100%;
}

@import '~@assets/less/common.less'
</style>
